// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfig) DeepCopyInto(out *AuthConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfig.
func (in *AuthConfig) DeepCopy() *AuthConfig {
	if in == nil {
		return nil
	}
	out := new(AuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthData) DeepCopyInto(out *AuthData) {
	*out = *in
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthData.
func (in *AuthData) DeepCopy() *AuthData {
	if in == nil {
		return nil
	}
	out := new(AuthData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCLPolicies) DeepCopyInto(out *HCLPolicies) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]PolicyPath, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCLPolicies.
func (in *HCLPolicies) DeepCopy() *HCLPolicies {
	if in == nil {
		return nil
	}
	out := new(HCLPolicies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntermediateOptions) DeepCopyInto(out *IntermediateOptions) {
	*out = *in
	if in.GenerateOptions != nil {
		in, out := &in.GenerateOptions, &out.GenerateOptions
		*out = new(VaultGenerateOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntermediateOptions.
func (in *IntermediateOptions) DeepCopy() *IntermediateOptions {
	if in == nil {
		return nil
	}
	out := new(IntermediateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTAuthConfig) DeepCopyInto(out *JWTAuthConfig) {
	*out = *in
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTAuthConfig.
func (in *JWTAuthConfig) DeepCopy() *JWTAuthConfig {
	if in == nil {
		return nil
	}
	out := new(JWTAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTRole) DeepCopyInto(out *JWTRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTRole.
func (in *JWTRole) DeepCopy() *JWTRole {
	if in == nil {
		return nil
	}
	out := new(JWTRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JWTRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTRoleList) DeepCopyInto(out *JWTRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JWTRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTRoleList.
func (in *JWTRoleList) DeepCopy() *JWTRoleList {
	if in == nil {
		return nil
	}
	out := new(JWTRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JWTRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTRoleParameters) DeepCopyInto(out *JWTRoleParameters) {
	*out = *in
	if in.BoundAudiences != nil {
		in, out := &in.BoundAudiences, &out.BoundAudiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BoundClaims != nil {
		in, out := &in.BoundClaims, &out.BoundClaims
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ClaimMappings != nil {
		in, out := &in.ClaimMappings, &out.ClaimMappings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.OIDCScopes != nil {
		in, out := &in.OIDCScopes, &out.OIDCScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedRedirectURLs != nil {
		in, out := &in.AllowedRedirectURLs, &out.AllowedRedirectURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TokenPolicies != nil {
		in, out := &in.TokenPolicies, &out.TokenPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTRoleParameters.
func (in *JWTRoleParameters) DeepCopy() *JWTRoleParameters {
	if in == nil {
		return nil
	}
	out := new(JWTRoleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTRoleSpec) DeepCopyInto(out *JWTRoleSpec) {
	*out = *in
	in.Parameters.DeepCopyInto(&out.Parameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTRoleSpec.
func (in *JWTRoleSpec) DeepCopy() *JWTRoleSpec {
	if in == nil {
		return nil
	}
	out := new(JWTRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTRoleStatus) DeepCopyInto(out *JWTRoleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTRoleStatus.
func (in *JWTRoleStatus) DeepCopy() *JWTRoleStatus {
	if in == nil {
		return nil
	}
	out := new(JWTRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIConfig) DeepCopyInto(out *PKIConfig) {
	*out = *in
	in.IntermediateOptions.DeepCopyInto(&out.IntermediateOptions)
	in.RootOptions.DeepCopyInto(&out.RootOptions)
	if in.URLs != nil {
		in, out := &in.URLs, &out.URLs
		*out = new(VaultEndpointConfigURLs)
		(*in).DeepCopyInto(*out)
	}
	if in.CRL != nil {
		in, out := &in.CRL, &out.CRL
		*out = new(VaultEndpointConfigCRL)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIConfig.
func (in *PKIConfig) DeepCopy() *PKIConfig {
	if in == nil {
		return nil
	}
	out := new(PKIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIRole) DeepCopyInto(out *PKIRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIRole.
func (in *PKIRole) DeepCopy() *PKIRole {
	if in == nil {
		return nil
	}
	out := new(PKIRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PKIRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIRoleBackendConfig) DeepCopyInto(out *PKIRoleBackendConfig) {
	*out = *in
	if in.Country != nil {
		in, out := &in.Country, &out.Country
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Locality != nil {
		in, out := &in.Locality, &out.Locality
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OU != nil {
		in, out := &in.OU, &out.OU
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Province != nil {
		in, out := &in.Province, &out.Province
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StreetAddress != nil {
		in, out := &in.StreetAddress, &out.StreetAddress
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedDomains != nil {
		in, out := &in.AllowedDomains, &out.AllowedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedURISANs != nil {
		in, out := &in.AllowedURISANs, &out.AllowedURISANs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtKeyUsage != nil {
		in, out := &in.ExtKeyUsage, &out.ExtKeyUsage
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtKeyUsageOIDs != nil {
		in, out := &in.ExtKeyUsageOIDs, &out.ExtKeyUsageOIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KeyUsage != nil {
		in, out := &in.KeyUsage, &out.KeyUsage
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PolicyIdentifiers != nil {
		in, out := &in.PolicyIdentifiers, &out.PolicyIdentifiers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIRoleBackendConfig.
func (in *PKIRoleBackendConfig) DeepCopy() *PKIRoleBackendConfig {
	if in == nil {
		return nil
	}
	out := new(PKIRoleBackendConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIRoleList) DeepCopyInto(out *PKIRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PKIRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIRoleList.
func (in *PKIRoleList) DeepCopy() *PKIRoleList {
	if in == nil {
		return nil
	}
	out := new(PKIRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PKIRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIRoleSpec) DeepCopyInto(out *PKIRoleSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIRoleSpec.
func (in *PKIRoleSpec) DeepCopy() *PKIRoleSpec {
	if in == nil {
		return nil
	}
	out := new(PKIRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIRoleStatus) DeepCopyInto(out *PKIRoleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIRoleStatus.
func (in *PKIRoleStatus) DeepCopy() *PKIRoleStatus {
	if in == nil {
		return nil
	}
	out := new(PKIRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyPath) DeepCopyInto(out *PolicyPath) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyPath.
func (in *PolicyPath) DeepCopy() *PolicyPath {
	if in == nil {
		return nil
	}
	out := new(PolicyPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RootOptions) DeepCopyInto(out *RootOptions) {
	*out = *in
	if in.GenerateOptions != nil {
		in, out := &in.GenerateOptions, &out.GenerateOptions
		*out = new(VaultGenerateOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RootOptions.
func (in *RootOptions) DeepCopy() *RootOptions {
	if in == nil {
		return nil
	}
	out := new(RootOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHRole) DeepCopyInto(out *SSHRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHRole.
func (in *SSHRole) DeepCopy() *SSHRole {
	if in == nil {
		return nil
	}
	out := new(SSHRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SSHRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHRoleList) DeepCopyInto(out *SSHRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SSHRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHRoleList.
func (in *SSHRoleList) DeepCopy() *SSHRoleList {
	if in == nil {
		return nil
	}
	out := new(SSHRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SSHRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHRoleParameters) DeepCopyInto(out *SSHRoleParameters) {
	*out = *in
	if in.DefaultCriticalOptions != nil {
		in, out := &in.DefaultCriticalOptions, &out.DefaultCriticalOptions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefaultExtensions != nil {
		in, out := &in.DefaultExtensions, &out.DefaultExtensions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AllowedUserKey != nil {
		in, out := &in.AllowedUserKey, &out.AllowedUserKey
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHRoleParameters.
func (in *SSHRoleParameters) DeepCopy() *SSHRoleParameters {
	if in == nil {
		return nil
	}
	out := new(SSHRoleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHRoleSpec) DeepCopyInto(out *SSHRoleSpec) {
	*out = *in
	in.Parameters.DeepCopyInto(&out.Parameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHRoleSpec.
func (in *SSHRoleSpec) DeepCopy() *SSHRoleSpec {
	if in == nil {
		return nil
	}
	out := new(SSHRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHRoleStatus) DeepCopyInto(out *SSHRoleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHRoleStatus.
func (in *SSHRoleStatus) DeepCopy() *SSHRoleStatus {
	if in == nil {
		return nil
	}
	out := new(SSHRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAuth) DeepCopyInto(out *VaultAuth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAuth.
func (in *VaultAuth) DeepCopy() *VaultAuth {
	if in == nil {
		return nil
	}
	out := new(VaultAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultAuth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAuthList) DeepCopyInto(out *VaultAuthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultAuth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAuthList.
func (in *VaultAuthList) DeepCopy() *VaultAuthList {
	if in == nil {
		return nil
	}
	out := new(VaultAuthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultAuthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAuthSpec) DeepCopyInto(out *VaultAuthSpec) {
	*out = *in
	out.Data = in.Data
	in.JWTConfig.DeepCopyInto(&out.JWTConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAuthSpec.
func (in *VaultAuthSpec) DeepCopy() *VaultAuthSpec {
	if in == nil {
		return nil
	}
	out := new(VaultAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAuthStatus) DeepCopyInto(out *VaultAuthStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAuthStatus.
func (in *VaultAuthStatus) DeepCopy() *VaultAuthStatus {
	if in == nil {
		return nil
	}
	out := new(VaultAuthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultEndpoint) DeepCopyInto(out *VaultEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultEndpoint.
func (in *VaultEndpoint) DeepCopy() *VaultEndpoint {
	if in == nil {
		return nil
	}
	out := new(VaultEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultEndpointConfigCRL) DeepCopyInto(out *VaultEndpointConfigCRL) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultEndpointConfigCRL.
func (in *VaultEndpointConfigCRL) DeepCopy() *VaultEndpointConfigCRL {
	if in == nil {
		return nil
	}
	out := new(VaultEndpointConfigCRL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultEndpointConfigURLs) DeepCopyInto(out *VaultEndpointConfigURLs) {
	*out = *in
	if in.IssuingCertificates != nil {
		in, out := &in.IssuingCertificates, &out.IssuingCertificates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CRLDistributionPoints != nil {
		in, out := &in.CRLDistributionPoints, &out.CRLDistributionPoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OSCPServers != nil {
		in, out := &in.OSCPServers, &out.OSCPServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultEndpointConfigURLs.
func (in *VaultEndpointConfigURLs) DeepCopy() *VaultEndpointConfigURLs {
	if in == nil {
		return nil
	}
	out := new(VaultEndpointConfigURLs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultEndpointList) DeepCopyInto(out *VaultEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultEndpointList.
func (in *VaultEndpointList) DeepCopy() *VaultEndpointList {
	if in == nil {
		return nil
	}
	out := new(VaultEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultEndpointSpec) DeepCopyInto(out *VaultEndpointSpec) {
	*out = *in
	out.MountOptions = in.MountOptions
	in.TuneOptions.DeepCopyInto(&out.TuneOptions)
	in.PKIConfig.DeepCopyInto(&out.PKIConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultEndpointSpec.
func (in *VaultEndpointSpec) DeepCopy() *VaultEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(VaultEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultEndpointStatus) DeepCopyInto(out *VaultEndpointStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultEndpointStatus.
func (in *VaultEndpointStatus) DeepCopy() *VaultEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(VaultEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultGenerateOptions) DeepCopyInto(out *VaultGenerateOptions) {
	*out = *in
	if in.Country != nil {
		in, out := &in.Country, &out.Country
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Locality != nil {
		in, out := &in.Locality, &out.Locality
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OU != nil {
		in, out := &in.OU, &out.OU
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Province != nil {
		in, out := &in.Province, &out.Province
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StreetAddress != nil {
		in, out := &in.StreetAddress, &out.StreetAddress
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PermittedDNSDomains != nil {
		in, out := &in.PermittedDNSDomains, &out.PermittedDNSDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultGenerateOptions.
func (in *VaultGenerateOptions) DeepCopy() *VaultGenerateOptions {
	if in == nil {
		return nil
	}
	out := new(VaultGenerateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultMountOptions) DeepCopyInto(out *VaultMountOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultMountOptions.
func (in *VaultMountOptions) DeepCopy() *VaultMountOptions {
	if in == nil {
		return nil
	}
	out := new(VaultMountOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultMountTuneOptions) DeepCopyInto(out *VaultMountTuneOptions) {
	*out = *in
	if in.AllowedResponseHeaders != nil {
		in, out := &in.AllowedResponseHeaders, &out.AllowedResponseHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultMountTuneOptions.
func (in *VaultMountTuneOptions) DeepCopy() *VaultMountTuneOptions {
	if in == nil {
		return nil
	}
	out := new(VaultMountTuneOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultNamespace) DeepCopyInto(out *VaultNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultNamespace.
func (in *VaultNamespace) DeepCopy() *VaultNamespace {
	if in == nil {
		return nil
	}
	out := new(VaultNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultNamespaceList) DeepCopyInto(out *VaultNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultNamespaceList.
func (in *VaultNamespaceList) DeepCopy() *VaultNamespaceList {
	if in == nil {
		return nil
	}
	out := new(VaultNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultNamespaceSpec) DeepCopyInto(out *VaultNamespaceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultNamespaceSpec.
func (in *VaultNamespaceSpec) DeepCopy() *VaultNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(VaultNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultNamespaceStatus) DeepCopyInto(out *VaultNamespaceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultNamespaceStatus.
func (in *VaultNamespaceStatus) DeepCopy() *VaultNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(VaultNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultPolicy) DeepCopyInto(out *VaultPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultPolicy.
func (in *VaultPolicy) DeepCopy() *VaultPolicy {
	if in == nil {
		return nil
	}
	out := new(VaultPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultPolicyList) DeepCopyInto(out *VaultPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultPolicyList.
func (in *VaultPolicyList) DeepCopy() *VaultPolicyList {
	if in == nil {
		return nil
	}
	out := new(VaultPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultPolicySpec) DeepCopyInto(out *VaultPolicySpec) {
	*out = *in
	in.Policies.DeepCopyInto(&out.Policies)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultPolicySpec.
func (in *VaultPolicySpec) DeepCopy() *VaultPolicySpec {
	if in == nil {
		return nil
	}
	out := new(VaultPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultPolicyStatus) DeepCopyInto(out *VaultPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultPolicyStatus.
func (in *VaultPolicyStatus) DeepCopy() *VaultPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(VaultPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultRole) DeepCopyInto(out *VaultRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultRole.
func (in *VaultRole) DeepCopy() *VaultRole {
	if in == nil {
		return nil
	}
	out := new(VaultRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultRoleData) DeepCopyInto(out *VaultRoleData) {
	*out = *in
	if in.BoundServiceAccountNames != nil {
		in, out := &in.BoundServiceAccountNames, &out.BoundServiceAccountNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BoundServiceAccountNamespaces != nil {
		in, out := &in.BoundServiceAccountNamespaces, &out.BoundServiceAccountNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecretIDBoundCIDRs != nil {
		in, out := &in.SecretIDBoundCIDRs, &out.SecretIDBoundCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TokenBoundCIDRs != nil {
		in, out := &in.TokenBoundCIDRs, &out.TokenBoundCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TokenPolicies != nil {
		in, out := &in.TokenPolicies, &out.TokenPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultRoleData.
func (in *VaultRoleData) DeepCopy() *VaultRoleData {
	if in == nil {
		return nil
	}
	out := new(VaultRoleData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultRoleList) DeepCopyInto(out *VaultRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultRoleList.
func (in *VaultRoleList) DeepCopy() *VaultRoleList {
	if in == nil {
		return nil
	}
	out := new(VaultRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultRoleSpec) DeepCopyInto(out *VaultRoleSpec) {
	*out = *in
	in.Data.DeepCopyInto(&out.Data)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultRoleSpec.
func (in *VaultRoleSpec) DeepCopy() *VaultRoleSpec {
	if in == nil {
		return nil
	}
	out := new(VaultRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultRoleStatus) DeepCopyInto(out *VaultRoleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultRoleStatus.
func (in *VaultRoleStatus) DeepCopy() *VaultRoleStatus {
	if in == nil {
		return nil
	}
	out := new(VaultRoleStatus)
	in.DeepCopyInto(out)
	return out
}
