# permissions for end users to view jwtroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jwtrole-viewer-role
rules:
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - jwtroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - jwtroles/status
  verbs:
  - get
