# permissions for end users to edit jwtroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jwtrole-editor-role
rules:
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - jwtroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - jwtroles/status
  verbs:
  - get
