# permissions for end users to view pkiroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pkirole-viewer-role
rules:
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - pkiroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - pkiroles/status
  verbs:
  - get
