# permissions for end users to edit secretmeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretmeta-editor-role
rules:
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - secretmeta
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - secretmeta/status
  verbs:
  - get
