# permissions for end users to view secretmeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretmeta-viewer-role
rules:
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - secretmeta
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - secretmeta/status
  verbs:
  - get
