# permissions for end users to view sshroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sshrole-viewer-role
rules:
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - sshroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - sshroles/status
  verbs:
  - get
