# permissions for end users to edit vaultendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultendpoint-editor-role
rules:
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - vaultendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - vaultendpoints/status
  verbs:
  - get
