# permissions for end users to view vaultendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultendpoint-viewer-role
rules:
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - vaultendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - vaultendpoints/status
  verbs:
  - get
