# permissions for end users to edit vaultauths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultauth-editor-role
rules:
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - vaultauths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - vaultauths/status
  verbs:
  - get
