# permissions for end users to edit vaultroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultrole-editor-role
rules:
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - vaultroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - vaultroles/status
  verbs:
  - get
