# permissions for end users to view vaultpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultpolicy-viewer-role
rules:
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - vaultpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - vaultpolicies/status
  verbs:
  - get
