# permissions for end users to edit vaultpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultpolicy-editor-role
rules:
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - vaultpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.vault-go.ibm.com
  resources:
  - vaultpolicies/status
  verbs:
  - get
