# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/vault.vault-go.ibm.com_vaultnamespaces.yaml
- bases/vault.vault-go.ibm.com_vaultpolicies.yaml
- bases/vault.vault-go.ibm.com_vaultroles.yaml
- bases/vault.vault-go.ibm.com_vaultauths.yaml
- bases/vault.vault-go.ibm.com_sshroles.yaml
- bases/vault.vault-go.ibm.com_pkiroles.yaml
- bases/vault.vault-go.ibm.com_jwtroles.yaml
- bases/vault.vault-go.ibm.com_vaultendpoints.yaml
- bases/vault.vault-go.ibm.com_secretmeta.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_vaultnamespaces.yaml
#- patches/webhook_in_vaultpolicies.yaml
#- patches/webhook_in_vaultroles.yaml
#- patches/webhook_in_vaultauths.yaml
#- patches/webhook_in_sshroles.yaml
#- patches/webhook_in_pkiroles.yaml
#- patches/webhook_in_jwtroles.yaml
#- patches/webhook_in_vaultendpoints.yaml
#- patches/webhook_in_secretmeta.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_vaultnamespaces.yaml
#- patches/cainjection_in_vaultpolicies.yaml
#- patches/cainjection_in_vaultroles.yaml
#- patches/cainjection_in_vaultauths.yaml
#- patches/cainjection_in_sshroles.yaml
#- patches/cainjection_in_pkiroles.yaml
#- patches/cainjection_in_jwtroles.yaml
#- patches/cainjection_in_vaultendpoints.yaml
#- patches/cainjection_in_secretmeta.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
